- hosts: all

  tasks:

   - package:     
        name: "httpd"
        state: present

   - service:
        name: "httpd"
        state: started
   
   - copy:
        dest: "/var/www/html"
        src: "/ws1/webs.html"

   - firewalld:
        port: "8080/tcp"
        permanent: yes
        state: enabled

